#!/bin/bash
#-----------------SSDS BY MARCO98-------------------
#------------------CONFIGURATION--------------------
NAME="SCREENNAME"
#NAME OF THE SCREEN INSTANCE
NEWUSER="USER"
#USER OF SCREEN PROCESS. EMPTY FOR NO SWITCH.
DIR="/WRK/DIR"
#WORKING DIRECTORY. EMPTY FOR NO SWITCH.
EXECCOMMAND="./FILETOEXECUTE"
#COMMAND TO EXECUTE
SHUTDOWNCMD="exit"
#IF EMPTY STRING "" CTRL-C WILL BE SENT.
#---------------------------------------------------
color() {
	local n="\033[0m"
	local g="\033[32m"
	local y="\033[33m"
	local r="\033[31m"
	eval "echo -en \"\$$1\""
	echo -e "$2$n"
}
running() {
	local out=$(screen -list | sed '1d' | sed '$d')
	if echo $out | grep -q $NAME
	then
		echo "true"
	else
		echo "false"
	fi
}
start() {
	if [ $(running) == "true" ]
	then
		color r "$NAME: Deamon is already active"
		exit 2
	fi
	if [[ -z "${NEWUSER// }" ]] || [[ "$USER" == "$NEWUSER" ]]
	then
		if [[ -z "${DIR// }" ]]
		then
			screen -AdmS $NAME bash -c "$EXECCOMMAND"
		else
			screen -AdmS $NAME bash -c "cd $DIR;$EXECCOMMAND"
		fi
	else
		if [[ -z "${DIR// }" ]]
		then
			screen -AdmS $NAME su $USER -s /bin/bash -c "$EXECCOMMAND"
		else
			screen -AdmS $NAME su $USER -s /bin/bash -c "cd $DIR;$EXECCOMMAND"
		fi
	fi
	color g "$NAME: Deamon started"
}
stop() {
	if ! [ $(running) == "true" ]
	then
		color r "$NAME: Deamon is inactive"
		exit 3
	fi
	if [[ -z "${SHUTDOWNCMD// }" ]]
	then
		screen -r -x $NAME -p 0 -X stuff ^C
	else
		screen -r -x $NAME -p 0 -X stuff "$(printf '\r')$SHUTDOWNCMD$(printf '\r')"
	fi
	printf "\033[32m$NAME: Shutdown signal has been sent..."
	while [ $(running) == "true" ]
	do
		sleep 1s
		printf "."
	done
	echo -en "\n"
}
restart() {
	stop
	start
}
status() {
	if [ $(running) == "true" ]
	then
		color g "$NAME: Deamon is active"
		exit 4
	else
		color r "$NAME: Deamon is inactive"
		exit 5
	fi
}
console() {
	if ! [ $(running) == "true" ]
	then
		color r "$NAME: Deamon is inactive"
		exit 6
	fi
	screen -r $NAME
}
own() {
	if ! [[ -z "${USER// }" ]]
	then
		chown -R $USER:$USER $DIR
	fi
}
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status
		;;
	restart)
		restart
		;;
	console)
		console
		;;
	chown)
		own
		;;
	*)
		echo "Usage: ./ssds {start|stop|restart|status|chown|console}"
		exit 1
		;;
esac
exit 0
